version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static/django/
      - media:/media/
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn --bind 0.0.0.0:8000 kittygram_backend.wsgi"

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
      - "443:443"
    volumes:
      - static:/static
      - media:/media/
    depends_on:
      - backend
      - frontend
