server {
    listen 80;
    server_name deadcatwithnobrainsinitsemptyhead.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    index index.html;
    server_name deadcatwithnobrainsinitsemptyhead.ru;

    ssl_certificate     /etc/letsencrypt/live/deadcatwithnobrainsinitsemptyhead.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/deadcatwithnobrainsinitsemptyhead.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:8000/api/;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:8000/admin/;
    }

    location /media/ {
        alias /media/;
    }

    location / {
        alias /static/;
        try_files $uri $uri/ /index.html;
    }
}